image: node:12.18.2-alpine

stages:
  - build
  - test
  - coverage
  - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build

test:
  stage: test
  script:
    - npm run test:ci
  artifacts:
    paths:
      - coverage
    untracked: false
    expire_in: 30 days
    
pages:
  stage: coverage
  dependencies:
    - test
  script:
    - mv coverage/lcov-report public
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

deploy:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish --tag latest --access public
